# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tideglass < Formula
  desc "Portable intent and preference profiles for local-first agents"
  homepage "https://github.com/vincentkoc/tideglass"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vincentkoc/tideglass/releases/download/v0.1.0/tideglass_0.1.0_darwin_amd64.tar.gz"
      sha256 "a80df20d464dcc4e0b9e13da1d4b8888d278ccf2d4de4fa8666ece0fb3659935"

      define_method(:install) do
        bin.install "tideglass"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vincentkoc/tideglass/releases/download/v0.1.0/tideglass_0.1.0_darwin_arm64.tar.gz"
      sha256 "681ee7d190f81f55d4a8be2de66bf4c3e4c52d0de218774531e57e8273241766"

      define_method(:install) do
        bin.install "tideglass"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vincentkoc/tideglass/releases/download/v0.1.0/tideglass_0.1.0_linux_amd64.tar.gz"
      sha256 "cea28d1c543c103136c746d4b542f6835ac80974972caf0d46d9c3d627e00235"
      define_method(:install) do
        bin.install "tideglass"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vincentkoc/tideglass/releases/download/v0.1.0/tideglass_0.1.0_linux_arm64.tar.gz"
      sha256 "ca9d0596ed9835d03a8bac6d27b02a7722bc7da76a98ddf9586a007b1a0bb1f0"
      define_method(:install) do
        bin.install "tideglass"
      end
    end
  end

  test do
    system bin/"tideglass", "version"
  end
end
